enable sriov-cni on arm platform
Currently, sriov-cni can't be build on arm64 platform
due to the undefined error in the library of golang during the compilation step.
such as:

./build
Building plugins
gopath/src/github.com/hustcat/sriov-cni/vendor/golang.org/x/sys/unix/flock.go:18: undefined: Flock_t

We should upgrade the version of 'golang.org/x/sys' and cni,
so that this issue will be gone.

Signed-off-by: Bin Lu <bin.lu@arm.com>